import { ArrowDownIcon, ArrowRightIcon, CircleAlertIcon, GitBranchIcon, IndianRupeeIcon, MapPinIcon, MessageSquareWarningIcon, NetworkIcon, RouteIcon } from 'lucide-react';
import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';

const steps = [['01', 'SELECT', 'Choose a tourism service, origin and destination.'], ['02', 'CONTEXTUALIZE', 'Retrieve the dataset route, distance and pricing context.'], ['03', 'ANALYZE', 'Evaluate price, complaints, location, patterns and text.'], ['04', 'EXPLAIN', 'Show the signals behind the overall score.'], ['05', 'ACT', 'Offer practical next steps before engagement.']];
const factors = [['PRICE ANOMALY', '30%', 'Contextual quote comparison and unusual pricing patterns.', IndianRupeeIcon], ['COMPLAINT HISTORY', '25%', 'Reported incidents grouped by service and location.', MessageSquareWarningIcon], ['LOCATION RISK', '20%', 'Nearby reports and hotspot density through PostGIS.', MapPinIcon], ['SERVICE PATTERN', '15%', 'Recurring service-location-complaint relationships.', NetworkIcon], ['TEXT SIGNAL', '10%', 'Semantically similar complaint descriptions.', GitBranchIcon]];
function normalizePageText() {
  const replacements: Record<string, string> = { '\u00e2\u201a\u00b9': '\u20b9', '\u00e2\u20ac\u201c': '\u2013', '\u00e2\u20ac\u201d': '\u2014', '\u00e2\u2020\u2019': '\u2192', '\u00c2\u00b7': '\u00b7', '\u00c2': '' };
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node: Node | null;
  while ((node = walker.nextNode())) {
    if (node.parentElement?.closest('script, style')) continue;
    let text = node.nodeValue ?? '';
    for (const [bad, good] of Object.entries(replacements)) text = text.split(bad).join(good);
    node.nodeValue = text;
  }
}
function Section({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="mx-auto max-w-[1100px] px-5 py-14 lg:py-18"><p className="text-[11px] font-semibold tracking-[0.15em] text-navy-500">{eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy">{title}</h2>{children}</section>; }
function Chain({ items }: { items: string[] }) { return <div className="mt-6 flex flex-col items-center gap-2">{items.map((item, index) => <React.Fragment key={item}><span className="border border-line bg-white px-4 py-2 text-xs font-semibold tracking-wide text-navy">{item}</span>{index < items.length - 1 && <ArrowDownIcon className="w-4 h-4 text-navy-500" />}</React.Fragment>)}</div>; }

export function About() {
  useEffect(() => { normalizePageText(); }, []);
  return <div className="w-full bg-white">
    <section className="relative overflow-hidden bg-navy text-white"><img src="/India.jpg" alt="" aria-hidden className="absolute inset-0 h-full w-full object-cover opacity-20" /><div className="absolute inset-0 bg-navy/70" aria-hidden /><div className="relative mx-auto max-w-[1100px] px-5 py-20 lg:py-28"><p className="text-[11px] font-semibold tracking-[0.16em] text-amber-200">ABOUT YATRASHIELD</p><h1 className="mt-4 max-w-3xl text-4xl lg:text-6xl font-semibold tracking-tight">Understanding YatraShield</h1><p className="mt-5 max-w-2xl text-base lg:text-lg leading-relaxed text-navy-100">An intelligent tourism-risk platform designed to help travelers recognize potential risk before engaging with unfamiliar services.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/risk-check" className="inline-flex items-center gap-2 bg-white px-5 py-3 text-xs font-semibold tracking-wide text-navy rounded-sm">CHECK A SERVICE <ArrowRightIcon className="w-3.5 h-3.5" /></Link><Link to="/risk-map" className="inline-flex items-center gap-2 border border-white/30 px-5 py-3 text-xs font-semibold tracking-wide text-white rounded-sm">EXPLORE RISK MAP</Link></div></div></section>
    <Section eyebrow="WHY YATRASHIELD?" title="Tourism should feel exciting, not uncertain."><div className="mt-5 max-w-3xl space-y-3 text-sm leading-relaxed text-charcoal-600"><p>Travelers often encounter unfamiliar transportation, tours, guides, rentals and local services where pricing, service history and complaint information may not be immediately clear.</p><p>YatraShield brings these signals together to provide contextual risk intelligence before a traveler pays, books or engages with a potentially suspicious service.</p></div><div className="mt-7 flex flex-wrap gap-3">{['Context-aware', 'Multi-signal', 'Explainable', 'Pre-transaction'].map((item) => <span key={item} className="border border-navy-100 bg-[#f4f7fa] px-3 py-2 text-xs font-semibold text-navy">{item}</span>)}</div></Section>
    <section className="border-y border-line bg-[#f4f7fa]"><Section eyebrow="THE PROBLEM TRAVELERS FACE" title="Information exists, but context is scattered."><div className="mt-8 grid md:grid-cols-3 gap-px border border-line bg-line rounded-sm overflow-hidden">{[['PRICE UNCERTAINTY', 'Is the quoted price reasonable for this route, service and context?', IndianRupeeIcon], ['SERVICE UNCERTAINTY', 'Have other travelers reported similar problems with this type of service?', MessageSquareWarningIcon], ['LOCATION UNCERTAINTY', 'Are recurring complaints concentrated around this location?', MapPinIcon]].map(([title, text, Icon]) => <article key={title as string} className="bg-white p-5"><Icon className="w-5 h-5 text-navy-500" /><h3 className="mt-4 text-xs font-semibold tracking-wide text-navy">{title as string}</h3><p className="mt-2 text-sm leading-relaxed text-charcoal-600">{text as string}</p></article>)}</div><p className="mt-5 text-sm text-charcoal-600">YatraShield turns these fragments into one contextual warning, without claiming to prove fraud.</p></Section></section>
    <Section eyebrow="OUR SOLUTION" title="From scattered signals to one contextual warning."><div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{[['TRAVELER', 'REQUEST'], ['SERVICE', '+ ROUTE'], ['DISTANCE', '+ CONTEXT'], ['PRICE', 'BENCHMARK'], ['RISK', 'ENGINE']].map(([a, b], index) => <div key={a} className="flex items-center gap-3"><div className="border border-line bg-[#f4f7fa] p-4 flex-1"><p className="text-[10px] font-semibold tracking-wide text-charcoal-400">{a}</p><p className="mt-1 text-xs font-semibold text-navy">{b}</p></div>{index < 4 && <ArrowRightIcon className="hidden lg:block w-4 h-4 text-navy-500" />}</div>)}</div><div className="mt-6 grid md:grid-cols-4 gap-3 text-center text-xs font-semibold text-navy"><span className="border border-line p-3">COMPLAINT ANALYSIS</span><span className="border border-line p-3">LOCATION ANALYSIS</span><span className="border border-line p-3">SERVICE PATTERNS</span><span className="border border-line p-3">EXPLAINABLE WARNING</span></div></Section>
    <section className="border-y border-line bg-[#f4f7fa]"><Section eyebrow="HOW IT WORKS" title="Five steps from a question to an action."><div className="mt-9 grid sm:grid-cols-2 lg:grid-cols-5 gap-6">{steps.map(([number, title, text]) => <article key={number}><span className="font-mono tabular text-2xl text-navy-500">{number}</span><h3 className="mt-3 text-xs font-semibold tracking-wide text-navy">{title}</h3><p className="mt-2 text-sm leading-relaxed text-charcoal-600">{text}</p></article>)}</div></Section></section>
    <Section eyebrow="ROUTE-AWARE CONTEXT" title="Risk begins with the right context."><div className="mt-7 grid md:grid-cols-2 gap-6"><div className="border border-line p-5"><p className="text-[10px] font-semibold tracking-wide text-charcoal-400">SUPPORTED TAXI ROUTE</p><Chain items={['TAXI', 'DELHI AIRPORT', 'CONNAUGHT PLACE', '15.4 KM']} /></div><div className="border border-line p-5"><p className="text-[10px] font-semibold tracking-wide text-charcoal-400">SUPPORTED BOAT ROUTE</p><Chain items={['BOAT RIDE', 'GATEWAY OF INDIA', 'ELEPHANTA ISLAND']} /></div></div><p className="mt-5 text-sm leading-relaxed text-charcoal-600">Different services operate on different routes. YatraShield filters incompatible combinations and uses the selected dataset route distance. Distance provides price context; it does not independently determine fraud risk.</p></Section>
    <section className="border-y border-line bg-[#f4f7fa]"><Section eyebrow="CONTEXTUAL PRICE BENCHMARKING" title="How do we know whether a price is unusual?"><p className="mt-4 max-w-3xl text-sm leading-relaxed text-charcoal-600">YatraShield does not use one fixed city-wide price. It prioritizes comparable observations for the same service and route, then considers distance bands, time, vehicle, luggage and toll context when exact route data is limited.</p><div className="mt-8 grid md:grid-cols-[0.8fr_1.2fr] border border-line bg-white rounded-sm overflow-hidden"><div className="p-6 bg-navy text-white"><dl className="space-y-4 text-sm">{[['SERVICE', 'Taxi'], ['ROUTE', 'Delhi Airport â†’ Connaught Place'], ['DISTANCE', '15.4 km'], ['TIME', 'Night'], ['VEHICLE', 'Sedan'], ['LUGGAGE', '2 bags'], ['TOLL', 'â‚¹100']].map(([key, value]) => <div key={key} className="flex justify-between gap-4 border-b border-white/10 pb-2"><dt className="text-navy-100/70">{key}</dt><dd className="text-right font-medium">{value}</dd></div>)}</dl></div><div className="p-6"><div className="grid sm:grid-cols-2 gap-5"><div><p className="text-[10px] font-semibold tracking-wide text-charcoal-400">EXPECTED PRICE</p><p className="mt-1 font-mono tabular text-2xl font-semibold text-navy">â‚¹750â€“â‚¹1,050</p></div><div><p className="text-[10px] font-semibold tracking-wide text-charcoal-400">QUOTED PRICE</p><p className="mt-1 font-mono tabular text-2xl font-semibold text-alert">â‚¹2,500</p></div><div><p className="text-[10px] font-semibold tracking-wide text-charcoal-400">BENCHMARK</p><p className="mt-1 font-mono tabular text-xl font-semibold text-navy">â‚¹900</p></div><div><p className="text-[10px] font-semibold tracking-wide text-charcoal-400">PRICE ANOMALY</p><p className="mt-1 text-xl font-semibold text-alert">HIGH</p></div></div><p className="mt-7 border-t border-line pt-4 text-xs leading-relaxed text-charcoal-600">Benchmark confidence and comparable observation count are shown with each result. Sparse data is labeled low confidence.</p></div></div></Section></section>
    <Section eyebrow="A NECESSARY DISTINCTION" title="Distance is context, not risk."><div className="mt-8 grid md:grid-cols-2 gap-5"><div className="border border-line p-5"><p className="text-xs font-semibold text-navy">ROUTE A Â· 15 KM</p><p className="mt-4 font-mono tabular text-lg text-charcoal">â‚¹2,500 quote</p><p className="mt-1 text-sm text-charcoal-600">Expected â‚¹750â€“â‚¹1,050</p><p className="mt-4 text-sm font-semibold text-alert">PRICE ANOMALY Â· HIGH</p></div><div className="border border-line p-5"><p className="text-xs font-semibold text-navy">ROUTE B Â· 300 KM</p><p className="mt-4 font-mono tabular text-lg text-charcoal">â‚¹5,000 quote</p><p className="mt-1 text-sm text-charcoal-600">Expected â‚¹4,500â€“â‚¹6,000</p><p className="mt-4 text-sm font-semibold text-good">PRICE ANOMALY Â· LOW</p></div></div><div className="mt-5 flex items-start gap-3 border-l-2 border-warn bg-[#fffaf0] p-4 text-sm leading-relaxed text-charcoal-600"><CircleAlertIcon className="w-5 h-5 text-warn shrink-0" />A longer route is not automatically riskier. Distance changes expected pricing; it does not independently determine fraud risk.</div></Section>
    <section className="border-y border-line bg-[#f4f7fa]"><Section eyebrow="MULTI-SIGNAL RISK ENGINE" title="One signal is rarely enough."><div className="mt-8 grid md:grid-cols-[1fr_auto_1fr] items-center gap-8"><div className="space-y-3">{factors.slice(0, 3).map(([name, weight, text, Icon]) => <div key={name} className="border border-line bg-white p-3"><div className="flex items-center gap-2 text-xs font-semibold text-navy"><Icon className="w-4 h-4" />{name}<span className="ml-auto font-mono">{weight}</span></div><p className="mt-2 text-xs text-charcoal-500">{text}</p></div>)}</div><div className="flex flex-col items-center"><div className="flex h-24 w-24 items-center justify-center rounded-full border-4 border-navy-100 bg-navy text-center text-xs font-semibold text-white">RISK<br />ENGINE</div><ArrowDownIcon className="mt-4 w-5 h-5 text-navy-500" /></div><div className="space-y-3">{factors.slice(3).map(([name, weight, text, Icon]) => <div key={name} className="border border-line bg-white p-3"><div className="flex items-center gap-2 text-xs font-semibold text-navy"><Icon className="w-4 h-4" />{name}<span className="ml-auto font-mono">{weight}</span></div><p className="mt-2 text-xs text-charcoal-500">{text}</p></div>)}<div className="border border-navy bg-white p-4 text-center font-mono tabular text-xl font-semibold text-alert">78 / 100 Â· HIGH RISK</div></div></div><p className="mt-6 text-sm text-charcoal-600">The existing weighting is 30% price, 25% complaints, 20% location, 15% service pattern and 10% text signal.</p></Section></section>
    <Section eyebrow="RECOMMENDATION ENGINE" title="Turning risk into an action."><div className="mt-8 grid md:grid-cols-2 gap-4">{[['HIGH PRICE ANOMALY', 'Ask for an itemized fare and compare nearby services.'], ['HIGH COMPLAINT HISTORY', 'Review recent reports before proceeding.'], ['SUSPICIOUS SERVICE PATTERN', 'Verify provider identity and service terms.'], ['MULTIPLE HIGH SIGNALS', 'Consider an alternative until pricing and provider details can be independently verified.']].map(([title, text]) => <div key={title} className="border-l-2 border-alert bg-[#f4f7fa] p-4"><p className="text-xs font-semibold tracking-wide text-navy">{title}</p><p className="mt-2 text-sm text-charcoal-600">{text}</p></div>)}</div></Section>
    <Section eyebrow="SYSTEM ARCHITECTURE + LIMITATIONS" title="Useful intelligence, responsibly presented."><div className="mt-8 grid md:grid-cols-3 gap-4 text-center text-xs font-semibold text-navy"><div className="space-y-3"><div className="border border-line p-4">TRAVELER</div><ArrowDownIcon className="mx-auto w-4 h-4" /><div className="border border-line p-4">REACT + TYPESCRIPT</div><ArrowDownIcon className="mx-auto w-4 h-4" /><div className="border border-line p-4">FASTAPI</div></div><div className="space-y-3"><div className="border border-navy bg-navy p-4 text-white">RISK ENGINE</div><p className="text-[11px] text-charcoal-500">Isolation Forest Â· Sentence Embeddings</p><div className="border border-line p-4">EXPLAINABLE WARNING</div></div><div className="space-y-3"><div className="border border-line p-4">POSTGRESQL + POSTGIS</div><ArrowDownIcon className="mx-auto w-4 h-4" /><div className="border border-line p-4">SUPABASE</div></div></div><div className="mt-8 grid md:grid-cols-2 gap-6 text-sm text-charcoal-600"><div><h3 className="text-xs font-semibold tracking-wide text-navy">PROTOTYPE DATA FOUNDATION</h3><p className="mt-3 leading-relaxed">Curated incident records, crowdsourced reports, price observations and synthetic validation data where live integrations are unavailable.</p></div><div><h3 className="text-xs font-semibold tracking-wide text-navy">LIMITATIONS</h3><p className="mt-3 leading-relaxed">Prices change. Models need quality observations. Multilingual interpretation can vary. A suspicious signal may be a false positive.</p></div></div><p className="mt-7 border-l-2 border-warn bg-[#fffaf0] p-4 text-sm text-charcoal-600">YatraShield provides decision support, not a definitive fraud verdict. Future scope includes verified providers, live price feeds, government integrations, multilingual NLP and real-time updates.</p></Section>
    <section className="bg-navy"><div className="mx-auto max-w-[1100px] px-5 py-14 flex flex-col md:flex-row md:items-center justify-between gap-6"><div><h2 className="text-3xl font-semibold tracking-tight text-white">Know the signals. Make the decision.</h2><p className="mt-2 text-sm text-navy-100">Explore potential risk before engaging with an unfamiliar tourism service.</p></div><div className="flex flex-wrap gap-3"><Link to="/risk-check" className="inline-flex items-center gap-2 bg-white text-navy px-5 py-3 text-xs font-semibold tracking-wide rounded-sm">CHECK A SERVICE <ArrowRightIcon className="w-3.5 h-3.5" /></Link><Link to="/risk-map" className="border border-white/30 text-white px-5 py-3 text-xs font-semibold tracking-wide rounded-sm">EXPLORE RISK MAP</Link></div></div></section>
  </div>;
}
