import { ArrowRightIcon, IndianRupeeIcon, MapPinIcon, MessageSquareWarningIcon, NetworkIcon } from 'lucide-react';
import React, { useEffect, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { RiskMapCanvas } from '../components/RiskMapCanvas';
import { useData } from '../contexts/DataContext';
import { riskPatterns } from '../data/patterns';
import { getHotspots, getIntelligenceSummary } from '../services/api';

const signals = [
  ['PRICE UNCERTAINTY', 'Is the quoted price reasonable for this route and service?', IndianRupeeIcon],
  ['SERVICE HISTORY', 'Have other travelers reported similar problems?', MessageSquareWarningIcon],
  ['LOCATION SIGNALS', 'Are recurring complaints clustered around this destination?', MapPinIcon],
];
const intelligence = [
  ['PRICE ANOMALIES', 'Contextual route benchmarks screen unusual pricing.', IndianRupeeIcon],
  ['LOCATION SIGNALS', 'PostGIS analysis surfaces nearby complaint clusters.', MapPinIcon],
  ['COMPLAINTS', 'Reports are grouped by service, location and category.', MessageSquareWarningIcon],
  ['SERVICE PATTERNS', 'Recurring service-location-complaint chains are tracked.', NetworkIcon],
];

function normalizePageText() {
  const replacements: Record<string, string> = {
    '\u00e2\u201a\u00b9': '\u20b9', '\u00e2\u20ac\u201c': '\u2013', '\u00e2\u20ac\u201d': '\u2014', '\u00e2\u2020\u2019': '\u2192', '\u00c2\u00b7': '\u00b7', '\u00c2': '',
  };
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node: Node | null;
  while ((node = walker.nextNode())) {
    if (node.parentElement?.closest('script, style')) continue;
    let text = node.nodeValue ?? '';
    for (const [bad, good] of Object.entries(replacements)) text = text.split(bad).join(good);
    node.nodeValue = text;
  }
}

export function Landing() {
  const { reports } = useData();
  useEffect(() => { normalizePageText(); }, []);
  const hotspots = useMemo(() => getHotspots(reports).filter((item) => item.reports > 0), [reports]);
  const summary = useMemo(() => getIntelligenceSummary(reports), [reports]);
  return <div className="w-full">
    <section className="relative min-h-[650px] overflow-hidden flex items-center"><img src="/India.jpg" alt="" aria-hidden className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-navy/75" aria-hidden /><div className="relative mx-auto max-w-[1240px] w-full px-5 py-16 grid lg:grid-cols-[1.05fr_0.95fr] gap-12 items-center"><div className="max-w-2xl"><p className="text-[11px] font-semibold tracking-[0.16em] text-amber-200">TOURISM RISK INTELLIGENCE</p><h1 className="mt-4 text-5xl lg:text-[64px] leading-[1.02] font-semibold text-white tracking-tight">Know the risk<br />before you engage.</h1><p className="mt-5 max-w-xl text-base lg:text-lg leading-relaxed text-white/85">Make confident travel decisions with clear signals from complaints, pricing patterns, locations and service history.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/risk-check" className="inline-flex items-center gap-2 bg-white px-5 py-3 text-xs font-semibold tracking-wide text-navy rounded-sm">CHECK A SERVICE <ArrowRightIcon className="w-3.5 h-3.5" /></Link><Link to="/risk-map" className="border border-white/30 px-5 py-3 text-xs font-semibold tracking-wide text-white rounded-sm">EXPLORE RISK MAP</Link><Link to="/about" className="px-2 py-3 text-xs font-semibold tracking-wide text-white/80">HOW IT WORKS</Link></div><dl className="mt-10 grid grid-cols-3 gap-5 max-w-lg border-t border-white/20 pt-5"><div><dt className="text-[10px] text-white/60 font-semibold tracking-wide">REPORTS ANALYZED</dt><dd className="mt-1 font-mono tabular text-2xl text-white">{summary.total_reports}</dd></div><div><dt className="text-[10px] text-white/60 font-semibold tracking-wide">ACTIVE HOTSPOTS</dt><dd className="mt-1 font-mono tabular text-2xl text-white">{summary.active_hotspots}</dd></div><div><dt className="text-[10px] text-white/60 font-semibold tracking-wide">PRICE ANOMALIES</dt><dd className="mt-1 font-mono tabular text-2xl text-white">{summary.price_anomalies}</dd></div></dl><p className="mt-3 text-[11px] text-white/55">Prototype intelligence dataset Â· Decision support, not a definitive fraud verdict.</p></div><div className="bg-white rounded-sm shadow-pop p-4"><div className="flex items-center justify-between px-2 py-1.5"><p className="text-[11px] font-semibold tracking-wide text-charcoal-400">LIVE RISK SURFACE Â· INDIA</p><Link to="/risk-map" className="text-[11px] font-semibold text-navy-500">OPEN MAP</Link></div><RiskMapCanvas hotspots={hotspots} compact height={390} /><div className="flex flex-wrap gap-4 px-2 pt-3 text-[11px] text-charcoal-600">{[['#157F4A', 'Low'], ['#B7791F', 'Medium'], ['#C2410C', 'High'], ['#B42318', 'Critical']].map(([color, label]) => <span key={label} className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: color }} />{label}</span>)}</div></div></div></section>

    <section className="mx-auto max-w-[1240px] px-5 py-16 lg:py-20"><div className="grid lg:grid-cols-[0.9fr_1.1fr] gap-10 items-center"><img src="/im5.jpg" alt="Indian tourism landscape" className="h-64 w-full object-cover rounded-sm" /><div><p className="text-[11px] font-semibold tracking-[0.15em] text-navy-500">ABOUT YATRASHIELD</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy">Tourism should feel exciting â€” not uncertain.</h2><p className="mt-4 text-sm leading-relaxed text-charcoal-600">YatraShield is an intelligent tourism-risk platform that combines reported incidents, location-specific complaints, contextual price benchmarks, service patterns and text signals to provide contextual warnings before engagement.</p><Link to="/about" className="mt-5 inline-flex items-center gap-2 text-xs font-semibold tracking-wide text-navy-500">ABOUT / HOW IT WORKS <ArrowRightIcon className="w-3.5 h-3.5" /></Link></div></div></section>

    <section className="border-y border-line bg-[#f4f7fa]"><div className="mx-auto max-w-[1240px] px-5 py-16"><p className="text-[11px] font-semibold tracking-[0.15em] text-navy-500">WHERE TRAVELERS FACE UNCERTAINTY</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy">The full picture is rarely in one place.</h2><div className="mt-8 grid md:grid-cols-3 gap-px border border-line bg-line rounded-sm overflow-hidden">{signals.map(([title, text, Icon]) => <article key={title as string} className="bg-white p-6"><Icon className="w-5 h-5 text-navy-500" /><h3 className="mt-4 text-xs font-semibold tracking-wide text-navy">{title as string}</h3><p className="mt-2 text-sm leading-relaxed text-charcoal-600">{text as string}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-[1240px] px-5 py-16" id="how-it-works"><p className="text-[11px] font-semibold tracking-[0.15em] text-navy-500">HOW YATRASHIELD TURNS SIGNALS INTO A SAFER DECISION</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy">Select â†’ contextualize â†’ analyze â†’ explain â†’ act.</h2><div className="mt-9 grid sm:grid-cols-2 lg:grid-cols-5 gap-6">{[['01', 'SELECT', 'Service + origin + destination'], ['02', 'CONTEXTUALIZE', 'Route distance + pricing context'], ['03', 'ANALYZE', 'Price + complaints + location'], ['04', 'EXPLAIN', 'Why the risk score changed'], ['05', 'ACT', 'Recommended next steps']].map(([num, title, text]) => <div key={num}><span className="font-mono tabular text-2xl text-navy-500">{num}</span><h3 className="mt-3 text-xs font-semibold tracking-wide text-navy">{title}</h3><p className="mt-2 text-sm text-charcoal-600">{text}</p></div>)}</div></section>

    <section className="border-y border-line bg-navy"><div className="mx-auto max-w-[1240px] px-5 py-16 grid lg:grid-cols-[0.85fr_1.15fr] gap-8 items-center"><div className="text-white"><p className="text-[11px] font-semibold tracking-[0.15em] text-navy-100/70">ONE QUOTE. MORE CONTEXT.</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Delhi Airport â†’ Connaught Place</h2><p className="mt-3 text-sm text-navy-100">Taxi Â· 15.4 km Â· Example scenario</p><p className="mt-8 font-mono tabular text-3xl">â‚¹2,500 <span className="text-sm text-navy-100">quoted</span></p></div><div className="bg-white rounded-sm p-6"><div className="grid sm:grid-cols-2 gap-5">{[['EXPECTED', 'â‚¹750â€“â‚¹1,050', 'text-navy'], ['PRICE ANOMALY', 'HIGH Â· +177.8%', 'text-alert'], ['COMPLAINTS', 'ELEVATED', 'text-warn'], ['SERVICE PATTERN', 'SUSPICIOUS', 'text-alert'], ['RISK', '78 / 100', 'text-alert']].map(([label, value, color]) => <div key={label} className="border-b border-line pb-3"><p className="text-[10px] font-semibold tracking-wide text-charcoal-400">{label}</p><p className={`mt-1 font-mono tabular text-lg font-semibold ${color}`}>{value}</p></div>)}</div><p className="mt-5 text-sm text-charcoal-600">Potential risk detected â€” verify before proceeding.</p></div></div></section>

    <section className="mx-auto max-w-[1240px] px-5 py-16"><div className="border border-line bg-[#f4f7fa] p-6 flex flex-col md:flex-row md:items-center gap-5"><div className="shrink-0"><p className="text-[11px] font-semibold tracking-wide text-navy-500">DISTANCE PROVIDES CONTEXT â€” IT IS NOT THE VERDICT</p><p className="mt-2 font-mono tabular text-sm text-charcoal">15 km Â· â‚¹2,500 â†’ unusual</p><p className="font-mono tabular text-sm text-charcoal">300 km Â· â‚¹5,000 â†’ reasonable</p></div><p className="text-sm leading-relaxed text-charcoal-600">The benchmark changes with route distance and context. A long journey is not automatically considered risky.</p></div></section>

    <section className="border-y border-line bg-[#f4f7fa]"><div className="mx-auto max-w-[1240px] px-5 py-16"><p className="text-[11px] font-semibold tracking-[0.15em] text-navy-500">MULTI-SIGNAL INTELLIGENCE</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy">One signal is rarely enough.</h2><div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-4 gap-px border border-line bg-line rounded-sm overflow-hidden">{intelligence.map(([title, text, Icon]) => <article key={title as string} className="bg-white p-5"><Icon className="w-5 h-5 text-navy-500" /><h3 className="mt-4 text-xs font-semibold tracking-wide text-navy">{title as string}</h3><p className="mt-2 text-sm text-charcoal-600">{text as string}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-[1240px] px-5 py-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-semibold tracking-[0.15em] text-navy-500">RISK MAP PREVIEW</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy">See where risk signals are emerging.</h2></div><Link to="/risk-map" className="inline-flex items-center gap-2 text-xs font-semibold tracking-wide text-navy-500">EXPLORE RISK MAP <ArrowRightIcon className="w-3.5 h-3.5" /></Link></div><div className="mt-8 border border-line rounded-sm p-3"><RiskMapCanvas hotspots={hotspots} compact height={300} /></div><p className="mt-3 text-[11px] text-charcoal-400">Prototype intelligence dataset Â· not live nationwide statistics.</p></section>

    <section className="border-t border-line"><div className="mx-auto max-w-[1240px] px-5 py-16"><p className="text-[11px] font-semibold tracking-[0.15em] text-navy-500">WHY YATRASHIELD?</p><div className="mt-6 grid md:grid-cols-3 gap-6">{[['CONTEXT-AWARE', 'Risk changes with service, route and pricing context.'], ['MULTI-SIGNAL', 'Price, complaints, location and service patterns work together.'], ['EXPLAINABLE', 'Users can see the signals behind a warning.']].map(([title, text]) => <article key={title} className="border-l-2 border-navy-100 pl-4"><h3 className="text-xs font-semibold tracking-wide text-navy">{title}</h3><p className="mt-2 text-sm text-charcoal-600">{text}</p></article>)}</div></div></section>

    <section className="relative overflow-hidden bg-navy"><img src="/Sunrise%20Over%20Varanasi%20Ghats.jpg" alt="" aria-hidden className="absolute inset-0 h-full w-full object-cover opacity-20" /><div className="relative mx-auto max-w-[1240px] px-5 py-16"><h2 className="text-3xl font-semibold text-white">Explore with confidence.</h2><p className="mt-2 text-sm text-navy-100">Check the signals before you engage with an unfamiliar tourism service.</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/risk-check" className="inline-flex items-center gap-2 bg-white px-5 py-3 text-xs font-semibold tracking-wide text-navy rounded-sm">CHECK A SERVICE <ArrowRightIcon className="w-3.5 h-3.5" /></Link><Link to="/risk-map" className="border border-white/30 px-5 py-3 text-xs font-semibold tracking-wide text-white rounded-sm">EXPLORE RISK MAP</Link><Link to="/emergency" className="border border-white/30 px-5 py-3 text-xs font-semibold tracking-wide text-white rounded-sm">EMERGENCY ASSISTANCE</Link></div></div></section>
  </div>;
}
