import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

export function Register() {
  const { register } = useAuth(); const navigate = useNavigate();
  const [form, setForm] = useState({ fullName: '', email: '', password: '', confirm: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (form.password !== form.confirm) { setError('Passwords do not match.'); return; } if (form.password.length < 8) { setError('Use at least 8 characters for your password.'); return; } setBusy(true); setError(''); try { await register(form.fullName, form.email, form.password); navigate('/dashboard'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create account.'); } finally { setBusy(false); } };
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="mx-auto max-w-[460px] px-5 py-16"><div className="border border-line bg-white rounded-sm p-6"><p className="text-[11px] font-semibold tracking-[0.14em] text-navy-500">YATRASHIELD ACCOUNT</p><h1 className="mt-3 text-3xl font-semibold text-navy tracking-tight">Create your account</h1><p className="mt-2 text-sm text-charcoal-600">Traveler accounts unlock saved checks and personalized safety context.</p><form className="mt-7 space-y-4" onSubmit={submit}>{[['fullName','FULL NAME','text'],['email','EMAIL','email'],['password','PASSWORD','password'],['confirm','CONFIRM PASSWORD','password']].map(([key,label,type]) => <label key={key} className="block text-[11px] font-semibold tracking-wide text-charcoal-400">{label}<input required type={type} className="mt-1.5 w-full border border-line rounded-sm px-3 py-2.5 text-sm" value={form[key as keyof typeof form]} onChange={(e) => set(key as keyof typeof form, e.target.value)} /></label>)}{error && <p role="alert" className="text-sm text-crit bg-crit-soft border border-crit/20 rounded-sm px-3 py-2">{error}</p>}<button disabled={busy} className="w-full bg-navy text-white text-xs font-semibold tracking-wide px-5 py-3 rounded-sm disabled:opacity-50">{busy ? 'CREATING ACCOUNT...' : 'CREATE TRAVELER ACCOUNT'}</button></form><p className="mt-5 text-sm text-charcoal-600">Already registered? <Link className="font-semibold text-navy-500" to="/login">Sign in</Link></p><p className="mt-4 text-[11px] text-charcoal-400">New accounts are travelers. Admin access is never selected here.</p></div></div>;
}
